services:
  nginxproxy:
    container_name: nginxproxy
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"